version: '3'

services:
  alerta:
    image: alerta/alerta-web
    container_name: alerta-web
    volumes:
      - $PWD/config/alertad.conf:/app/alertad.conf
    ports:
      - 8080:8080
    depends_on:
      - alerta-db
    environment:
      - DEBUG=1  # remove this line to turn DEBUG off
      - DATABASE_URL=postgres://postgres:postgres@alerta-db:5432/monitoring
      - AUTH_REQUIRED=True
      - ADMIN_USERS=admin@alerta.io,devops@alerta.io
      - PLUGINS=reject,blackout,normalise,enhance
      - INSTALL_PLUGINS=normalise,enhance
    restart: always
  alerta-db:
    image: postgres
    container_name: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always

  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: keycloak-db
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - keycloak-db
  keycloak-db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password

volumes:
  postgres_data:
      driver: local
